version: '3'
services:
  mongo:
    image: mongo:5.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./dump/prestamax:/dump
