import type { NextPage } from 'next';
import styled from 'styled-components';
import Head from 'next/head';

const Title = styled.h1`
  color: red;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PrestaMax</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title>PrestaMax</Title>
      </main>
    </div>
  );
};

export default Home;
